---
title: "Track I: Report and publish"
format: html
---

# Instructions

For this final milestone, showcase your project by creating a Quarto report in one of the following formats:

* HTML report: https://quarto.org/docs/output-formats/html-basics.html (possibly with parameters: https://quarto.org/docs/computations/parameters.html)
* Slideshow: https://quarto.org/docs/presentations/revealjs/
* Dashboard: https://quarto.org/docs/dashboards/

Your report should bring together code from previous milestones (add new code if you wish) to tell a coherent story of either:

a) the project data (via your project-based extensions) or
b) your own data (if you have worked with your own data in extensions)

When you're done, publish your report to Posit Connect to share with your teammates. The link for publishing to Connect will automatically be populated for you during the publishing process. (You can find that link in the Publish step of the Connect publishing interface.) See here for an overview of how to publish to Connect: https://docs.posit.co/connect/user/publishing-rstudio/

As you work on this milestone, you may want to refer to the following pages from the Quarto docs:

* Markdown Basics: https://quarto.org/docs/authoring/markdown-basics.html
* HTML Basics: https://quarto.org/docs/output-formats/html-basics.html
* Execution Options: https://quarto.org/docs/computations/execution-options.html
* Quarto Cheatsheet: https://rstudio.github.io/cheatsheets/quarto.pdf

# Milestone

## Report and publish

(Create your Quarto report here, or start a new Quarto document.)
